import { CARDS } from '../data/cards.js'
import { CATEGORY_COLORS } from '../data/categories.js'
import { BG, TEXT, text } from '../lib/theme.js'
import { ComparisonView } from '../components/ComparisonView.jsx'

// ─── SHARED PROFILE LANDING ───────────────────────────────────────────────────
// Shown when someone opens a `?p=` share link generated by ProfileScreen's
// "Share"/"Copy Link" buttons.
//
// Two modes:
//  • Viewer has already taken the quiz (`viewer` present) → show the two-sided
//    comparison immediately (the viral payoff — "you two are 84% aligned").
//  • Brand-new viewer → the original archetype-teaser landing; the friend link
//    is stashed by Router so the comparison resurfaces after they onboard.

export function SharedProfileScreen({ shared, viewer, onContinue }) {
  const { archetype, likedIds } = shared
  const likedCards = likedIds.map(id => CARDS.find(c => c.id === id)).filter(Boolean)

  if (viewer?.archetype && viewer?.liked?.length) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center px-6" style={{ background: BG }}>
        <ComparisonView
          mine={{ archetype: viewer.archetype, liked: viewer.liked }}
          theirs={{ archetype, likedCards }}
          onContinue={onContinue}
          continueLabel="Continue to my profile →"
        />
      </div>
    )
  }

  const teaserCards = likedCards.slice(0, 6)
  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-6 text-center" style={{ background: BG }}>
      <div className="w-full max-w-xs">
        <p className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: '#fd297b' }}>Someone shared their archetype</p>
        <div className="text-6xl mb-3 animate-float">{archetype.emoji}</div>
        <h1 className="text-2xl font-bold mb-2 leading-tight" style={{ fontFamily: 'Fraunces, serif', letterSpacing: '-0.03em', color: TEXT }}>
          {archetype.name}
        </h1>
        <p className="text-sm leading-relaxed mb-6" style={{ color: text(0.4) }}>
          {archetype.description}
        </p>

        {teaserCards.length > 0 && (
          <div className="flex flex-wrap justify-center gap-1.5 mb-8">
            {teaserCards.map(c => (
              <span key={c.id} className="px-3 py-1.5 rounded-full text-sm"
                style={{ background: `${CATEGORY_COLORS[c.category]}12`, color: CATEGORY_COLORS[c.category], border: `1px solid ${CATEGORY_COLORS[c.category]}28` }}>
                {c.emoji} {c.label}
              </span>
            ))}
          </div>
        )}

        <button onClick={onContinue}
          className="w-full py-4 rounded-2xl text-black font-bold text-base transition-all duration-200 hover:scale-[1.02]"
          style={{ background: 'linear-gradient(135deg,#fd297b,#ff655b)', boxShadow: '0 0 40px rgba(253,41,123,0.25)' }}>
          Find out how you compare →
        </button>
      </div>
    </div>
  )
}
