import { CARDS } from '../data/cards.js'
import { CATEGORY_COLORS } from '../data/categories.js'
import { BG, TEXT, text } from '../lib/theme.js'

// ─── SHARED PROFILE LANDING ───────────────────────────────────────────────────
// Shown when someone opens a `?p=` share link generated by ProfileScreen's
// "Share"/"Copy Link" buttons. Previously that link decoded to nothing —
// it just silently loaded the normal app with no acknowledgment of the share.

export function SharedProfileScreen({ shared, onContinue }) {
  const { archetype, likedIds } = shared
  const likedCards = likedIds.map(id => CARDS.find(c => c.id === id)).filter(Boolean).slice(0, 6)

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-6 text-center" style={{ background: BG }}>
      <div className="w-full max-w-xs">
        <p className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: '#8b5cf6' }}>Someone shared their archetype</p>
        <div className="text-6xl mb-3 animate-float">{archetype.emoji}</div>
        <h1 className="text-2xl font-bold mb-2 leading-tight" style={{ fontFamily: 'Fraunces, serif', letterSpacing: '-0.03em', color: TEXT }}>
          {archetype.name}
        </h1>
        <p className="text-sm leading-relaxed mb-6" style={{ color: text(0.4) }}>
          {archetype.description}
        </p>

        {likedCards.length > 0 && (
          <div className="flex flex-wrap justify-center gap-1.5 mb-8">
            {likedCards.map(c => (
              <span key={c.id} className="px-3 py-1.5 rounded-full text-sm"
                style={{ background: `${CATEGORY_COLORS[c.category]}12`, color: CATEGORY_COLORS[c.category], border: `1px solid ${CATEGORY_COLORS[c.category]}28` }}>
                {c.emoji} {c.label}
              </span>
            ))}
          </div>
        )}

        <button onClick={onContinue}
          className="w-full py-4 rounded-2xl text-black font-bold text-base transition-all duration-200 hover:scale-[1.02]"
          style={{ background: 'linear-gradient(135deg,#fd297b,#ff655b)', boxShadow: '0 0 40px rgba(253,41,123,0.25)' }}>
          Find out what you are →
        </button>
      </div>
    </div>
  )
}
